apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-icaplat-sit
  namespace: icaplat-sit
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: icaplat-sit-pv