apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 0
      initContainers:
        - name: volume-permissions
          image: ${ICAPLAT_K8S_IMAGE_ALPINE}
          command: [ 'sh', '-c', '[ ! -f /permissions/mysql.done ] && chown -R 999 /var/lib/mysql && chmod -R g+rwX /var/lib/mysql && touch /permissions/mysql.done || true' ]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
              subPath: mysql
            - mountPath: /permissions
              name: mysql-storage
              subPath: init-perms
      containers:
        - image: ${ICAPLAT_K8S_IMAGE_MYSQL}
          imagePullPolicy: Never
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          name: mysql
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --max_connections=10240
            - --lower_case_table_names=1
            - --max_allowed_packet=32M
            - --default-time_zone=+8:00
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: sysmgt
            - name: MYSQL_USER
              value: sysmgt
            - name: MYSQL_PASSWORD
              value: UnionBigData!123.
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: '0.01'
              memory: 512Mi
          ports:
            - containerPort: 3306
#          volumeMounts:
#            - mountPath: /var/lib/mysql
#              name: mysql-storage
#              subPath: mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: pvc-${ICAPLAT_K8S_MAIN_NAMESPACE}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      name: default3306
      targetPort: 3306
  selector:
    app: mysql
