unionbigdata:
  default-resource-name: datamgt
  feign-service:
    database-info:
      kettle-sync: false
feign:
  compression:
    request:
      min-request-size: 4096

spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${unionbigdata.mysql.host}:${unionbigdata.mysql.port}/xs_database?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowMultiQueries=true
          username: ${unionbigdata.mysql.username}
          password: ${unionbigdata.mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            publicKey: ${unionbigdata.mysql.publicKey}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /manage
  health:
    elasticsearch:
      enabled: false
    mongo:
      enabled: false
  server:
    port: 8080
