# nginx-service-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport-30080
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080              # Kubernetes 集群内部的访问端口
      targetPort: 80
      nodePort: 30080       # 指定的集群外部访问端口 (可选)
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-service-nodeport-30081
#spec:
#  type: NodePort
#  selector:
#    app: nginx
#  ports:
#    - protocol: TCP
#      port: 8081              # Kubernetes 集群内部的访问端口
#      targetPort: 80
#      nodePort: 30081       # 指定的集群外部访问端口 (可选)
