apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 1001
      initContainers:
        - name: volume-permissions
          image: harbor.xnunion.com/cpyfreg/icaplat/arm64/baseon/alpine:3.16
          command: [ 'sh', '-c', '[ ! -f /permissions/kafka.done ] && chown -R 1001 /bitnami/kafka && chmod -R g+rwX /bitnami/kafka && touch /permissions/kafka.done || true' ]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - mountPath: /bitnami/kafka
              name: kafka-storage
              subPath: kafka
            - mountPath: /permissions
              name: kafka-storage
              subPath: init-perms
      containers:
        - image: harbor.xnunion.com/arm64v8/kafka:3.3
          imagePullPolicy: Never
          name: kafka
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: APP:PLAINTEXT,CONTROLLER:PLAINTEXT,ALG:PLAINTEXT
            - name: KAFKA_CFG_LISTENERS
              value: APP://:9092,CONTROLLER://:9093,ALG://0.0.0.0:19092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: APP://kafka:9092,ALG://kafka.icaplat-sit.svc.cluster.local:19092
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: APP
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 1@127.0.0.1:9093
          resources:
            limits:
              cpu: '4'
              memory: 4Gi
            requests:
              cpu: '0.01'
              memory: 256Mi
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 19092
          volumeMounts:
            - mountPath: /bitnami/kafka
              name: kafka-storage
              subPath: kafka
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: pvc-icaplat-sit
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
      name: app9092
      targetPort: 9092
    - port: 19092
      name: alg19092
      targetPort: 19092
  selector:
    app: kafka