apiVersion: v1
kind: Service
metadata:
  name: postgresql-nodeport
spec:
  selector:
    app: postgresql
  type: NodePort
  ports:
    - name: 5432tcp31003
      nodePort: 31003
      port: 5432
      targetPort: 5432