apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    cattle.io/creator: norman
  name: icaplat-sit-dev-notebook-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /data/icaplat-sit
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    cattle.io/creator: norman
  name: icaplat-sit-estimate-model-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /data/icaplat-sit
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    cattle.io/creator: norman
  name: icaplat-sit-serving-model-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /data/icaplat-sit
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    cattle.io/creator: norman
  name: icaplat-sit-train-automodel-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /data/icaplat-sit
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    cattle.io/creator: norman
  name: icaplat-sit-train-workflow-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /data/icaplat-sit
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    cattle.io/creator: norman
  name: icaplat-sit-serving-workflow-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /data/icaplat-sit
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    cattle.io/creator: norman
  name: icaplat-sit-transformer-model-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  local:
    path: /data/icaplat-sit
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
