kind: ServiceAccount
apiVersion: v1
metadata:
  name: icaplat
  namespace: icaplat-sit-train-workflow
  labels:
    icaplat.app/name: icaplat
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    icaplat.app/name: icaplat
  name: icaplat
  namespace: icaplat-sit-train-workflow
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    icaplat.app/name: icaplat
  name: icaplat
  namespace: icaplat-sit-train-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: icaplat
subjects:
  - kind: ServiceAccount
    name: icaplat
    namespace: icaplat-sit-train-workflow
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: icaplat
  namespace: icaplat-sit-serving-workflow
  labels:
    icaplat.app/name: icaplat
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    icaplat.app/name: icaplat
  name: icaplat
  namespace: icaplat-sit-serving-workflow
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    icaplat.app/name: icaplat
  name: icaplat
  namespace: icaplat-sit-serving-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: icaplat
subjects:
  - kind: ServiceAccount
    name: icaplat
    namespace: icaplat-sit-serving-workflow
