apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx-1
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx-2
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: docker.io/library/nginx:alpine
