apiVersion: v1
kind: Pod
metadata:
  name: train-automodel-no-volumes-mindspore-resnet
  namespace: icaplat-sit-train-automodel
spec:
  containers:
  - args:
    - -c
    - sleep 100000
    command:
    - /bin/bash
    image: unionbigdata/root_ascend-mindspore:0.1.0-A1
    imagePullPolicy: IfNotPresent
    name: train-automodel-5-31
    resources:
      limits:
        cpu: "24"
        memory: 16192Mi
      requests:
        cpu: "24"
        memory: 16192Mi

