apiVersion: v1
kind: Pod
metadata:
  name: wrk-pod
  labels:
    purpose: test-wrk
spec:
  containers:
  - name: wrk
    image: simonmittag/wrk:go1.21
    command: ["sleep", "1000"]  # Override the default CMD
    volumeMounts:
    - name: wrk-scripts
      mountPath: /app/scripts
  volumes:
  - name: wrk-scripts
    hostPath:
      path: /data/szl1160710/scripts/mindspore_inference_service/wrk
      type: Directory

