FROM image.sourcefind.cn:5000/dcu/admin/base/pytorch:1.13.1-ubuntu20.04-dtk23.10-py39

LABEL maintainer="chenxing@unionbigdata.com"

# Infrastructure:

# Business Lib:

# Port Design:

CMD ["/bin/bash"]
