FROM image.sourcefind.cn:5000/dcu/admin/base/pytorch:1.13.1-ubuntu20.04-dtk23.10-py39

LABEL maintainer="chenxing@unionbigdata.com"

# Infrastructure: torchserve torch-model-archiver
RUN pip3 install torchserve torch-model-archiver

# Business Lib:

# Port Design:

CMD ["/bin/bash"]
