apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: icaplat-algorithm-web
  name: icaplat-algorithm-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icaplat-algorithm-web
  template:
    metadata:
      labels:
        app: icaplat-algorithm-web
    spec:
      containers:
        - name: icaplat-algorithm-web
          image: icaplat/arm64/dev/icaplat-algorithm-web:4.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 50Mi
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: icaplat-algorithm-web
  name: icaplat-algorithm-web
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: icaplat-algorithm-web