apiVersion: apps/v1
kind: Deployment
metadata:
  name: icaplat-gateway
  labels:
    app: icaplat-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icaplat-gateway
  template:
    metadata:
      labels:
        app: icaplat-gateway
    spec:
      containers:
        - name: icaplat-gateway
          image: harbor.xnunion.com/cpyfreg/icaplat/lcr/dev/icaplat-gateway:4.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          startupProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 20
            tcpSocket:
              port: 80
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '0.1'
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: icaplat-gateway
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: icaplat-gateway