FROM unionbigdata/notebook_ascend-mindspore:0.1.0
#COPY --chown=HwHiAiUser:HwHiAiUser --chmod=755 mindspore_fcn8s/ /home/HwHiAiUser/mindspore_fcn8s/
COPY --chown=HwHiAiUser:HwHiAiUser mindspore_fcn8s/ /home/HwHiAiUser/mindspore_fcn8s/
USER HwHiAiUser

