FROM ascendhub.huawei.com/public-ascendhub/ascend-mindspore:23.0.0-A1-ubuntu18.04

LABEL maintainer="chenxing@unionbigdata.com"

USER root

# Business Lib:
RUN pip3 install download==0.3.5
RUN pip3 install opencv-python==4.9.0.80
RUN pip3 install matplotlib==3.5.3

