apiVersion: v1
kind: Pod
metadata:
  name: dcu-mobilenetv3-pytorch
  labels:
    purpose: demo-dcu-mobilenetv3-pytorch
spec:
  containers:
    - name: dcu-mobilenetv3-pytorch
      image: image.sourcefind.cn:5000/dcu/admin/base/pytorch:1.10.0-centos7.6-dtk-22.10-py38-latest
      workingDir: /data/mobilenetv3_pytorch
      command: ["/bin/bash", "train.sh"]
      resources:
        limits:
          memory: "32Gi"
          hygon.com/dcu: 2 # requesting a GPU
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      hostPath:
        path: /home/szl1160710/scripts/dcu_pytorch_sample_model_zoo/data

