apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"postgresql"},"name":"postgresql","namespace":"icaplat-sit"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"postgresql"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"postgresql"}},"spec":{"containers":[{"env":[{"name":"POSTGRES_USER","value":"icaplat"},{"name":"POSTGRES_PASSWORD","value":"UnionBigData_123."},{"name":"shared_buffers","value":"128MB"}],"image":"harbor.xnunion.com/cpyfreg/middleware/arm64/third/postgres:14-alpine3.16","imagePullPolicy":"IfNotPresent","name":"postgresql","ports":[{"containerPort":5432}],"resources":{"limits":{"cpu":"8","hugepages-2Mi":"512Mi","memory":"8Gi"},"requests":{"cpu":"0.1","memory":"2Gi"}}}],"initContainers":[{"command":["sh","-c","[ ! -f /permissions/postgresql.done ] \u0026\u0026 chown -R 70 /var/lib/postgresql \u0026\u0026 chmod -R g+rwX /var/lib/postgresql \u0026\u0026 touch /permissions/postgresql.done || true"],"image":"harbor.xnunion.com/cpyfreg/icaplat/arm64/baseon/alpine:3.16","name":"volume-permissions","securityContext":{"runAsGroup":0,"runAsUser":0},"volumeMounts":[{"mountPath":"/var/lib/postgresql/data","name":"postgresql-storage","subPath":"postgresql"},{"mountPath":"/permissions","name":"postgresql-storage","subPath":"init-perms"}]},{"command":["sh","-c","[ -f /var/lib/postgresql/data/PG_VERSION ] \u0026\u0026 pg_resetwal /var/lib/postgresql/data || true"],"image":"harbor.xnunion.com/cpyfreg/icaplat/arm64/baseon/alpine:3.16","name":"postgresql-reset-wal","securityContext":{"runAsGroup":0,"runAsUser":0},"volumeMounts":[{"mountPath":"/var/lib/postgresql/data","name":"postgresql-storage","subPath":"postgresql"}]}],"securityContext":{"runAsUser":70},"volumes":[{"name":"postgresql-storage","persistentVolumeClaim":{"claimName":"pvc-icaplat-sit"}}]}}}}
  creationTimestamp: "2024-04-24T09:53:39Z"
  generation: 1
  labels:
    app: postgresql
  name: postgresql
  namespace: icaplat-sit
  resourceVersion: "3010006"
  uid: e68a97d9-0809-412b-ae4d-6ffe4e595d24
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: icaplat
        - name: POSTGRES_PASSWORD
          value: UnionBigData_123.
        - name: shared_buffers
          value: 128MB
        image: pg14:bullseyes
        imagePullPolicy: IfNotPresent
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          limits:
            cpu: "8"
            hugepages-2Mi: 512Mi
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 2Gi
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgresql-storage
            subPath: postgresql
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - '[ ! -f /permissions/postgresql.done ] && chown -R 70 /var/lib/postgresql
          && chmod -R g+rwX /var/lib/postgresql && touch /permissions/postgresql.done
          || true'
        image: harbor.xnunion.com/cpyfreg/icaplat/arm64/baseon/alpine:3.16
        imagePullPolicy: IfNotPresent
        name: volume-permissions
        resources: {}
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-storage
          subPath: postgresql
        - mountPath: /permissions
          name: postgresql-storage
          subPath: init-perms
      - command:
        - sh
        - -c
        - '[ -f /var/lib/postgresql/data/PG_VERSION ] && pg_resetwal /var/lib/postgresql/data
          || true'
        image: harbor.xnunion.com/cpyfreg/icaplat/arm64/baseon/alpine:3.16
        imagePullPolicy: IfNotPresent
        name: postgresql-reset-wal
        resources: {}
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-storage
          subPath: postgresql
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 70
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: pvc-icaplat-sit
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-24T09:53:52Z"
    lastUpdateTime: "2024-04-24T09:53:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-24T09:53:39Z"
    lastUpdateTime: "2024-04-24T09:53:52Z"
    message: ReplicaSet "postgresql-579954c8fc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
