apiVersion: v1
kind: Pod
metadata:
  name: dcu-torchserve
  labels:
    purpose: demo-torchserve
spec:
  restartPolicy: OnFailure
  containers:
    - name: torchserve
      #image: image.sourcefind.cn:5000/dcu/admin/base/pytorch:1.10.0-centos7.6-dtk-22.10-py38-latest
      image: unionbigdata/torchserve_dcu-pytorch:1.13.1-ubuntu20.04-dtk23.10-v1
      workingDir: /data/
      command: ["/bin/bash", "-c", "sleep 1000"]
      resources:
        limits:
          memory: "32Gi"
          hygon.com/dcu: 2 # requesting a GPU
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      hostPath:
        path: /home/szl1160710/script/dcu_torchserve/data
