apiVersion: v1
kind: Service
metadata:
  name: gpu-manager-metric
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metric"
    prometheus.io/port: "5678"
  labels:
    kubernetes.io/cluster-service: "true"
    name: gpu-manager-metric
spec:
  #clusterIP: None
  ports:
    - name: metrics
      port: 5678
      protocol: TCP
      targetPort: 5678
  selector:
    name: gpu-manager-ds
    #name: gpu-manager-daemonset
