apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: jupyter-notebook
        image: unionbigdata/notebook_ascend-mindspore:0.1.0
        ports:
        - containerPort: 30081
        volumeMounts:
        - name: mindspore-volume
          mountPath: /home/HwHiAiUser/mindspore_fcn8s
        resources:
          limits:
            huawei.com/Ascend910: 1
          requests:
            huawei.com/Ascend910: 1
      volumes:
      - name: mindspore-volume
        hostPath:
          path: /data/szl1160710/scripts/mindspore_docker_build/volumes/mindspore_fcn8s
          type: Directory

---

apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 30081
    targetPort: 30081
    nodePort: 30081
  selector:
    app: jupyter-notebook
