apiVersion: v1
kind: Pod
metadata:
  labels:
    icaplat.app/name: train-automodel-4-2
    icaplat.app/train: automodel
    icaplat.app/type: algorithm
    icaplat.logging/collect: "true"
  name: train-automodel-4-2-772ks
  namespace: icaplat-sit-train-automodel
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: unionbigdata.com/product_instance_cnt
            operator: In
            values:
            - "1"
        weight: 20
      - preference:
          matchExpressions:
          - key: unionbigdata.com/product_instance.icaplat
            operator: In
            values:
            - "true"
        weight: 20
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: unionbigdata.com/product_instance.icaplat
            operator: In
            values:
            - "true"
        - matchExpressions:
          - key: unionbigdata.com/product_instance_cnt
            operator: In
            values:
            - "0"
        - matchExpressions:
          - key: unionbigdata.com/product_instance_cnt
            operator: DoesNotExist
  containers:
  - args:
    - -c
    - cd /workspace && python train.py --config configs.json
    command:
    - /bin/bash
    env:
    - name: GpuNumber
      value: "0"
    - name: TrainTaskId
      value: "2"
    - name: Parallelism
      value: "1"
    - name: EtcdAddress
      value: etcd.icaplat-sit.svc.cluster.local:2379
    image: unionbigdata/root_ascend-pytorch:0.1.0
    imagePullPolicy: IfNotPresent
    name: train-automodel-4-2
    resources:
      limits:
        cpu: "16"
        memory: 32Gi
      requests:
        cpu: "16"
        memory: 32Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: shm
    - mountPath: /workspace
      name: vol-index0-number0
      subPath: train/algplat/one/am4/2/12
    - mountPath: /workspace/input/dataset/batch-size/Images
      name: vol-index0-number0
      readOnly: true
      subPath: dataset/algplat/one/5
    - mountPath: /workspace/input/dataset/epochs/Images
      name: vol-index0-number0
      readOnly: true
      subPath: dataset/algplat/one/5
    - mountPath: /workspace/input/dataset/another-input/Images
      name: vol-index0-number0
      readOnly: true
      subPath: dataset/algplat/one/5
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 10Gi
    name: shm
  - name: vol-index0-number0
    persistentVolumeClaim:
      claimName: pvc-icaplat-sit
  - name: kube-api-access-wctsb
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

